CREATE
	TABLE
		"DBINTGEN" . "SERVICIO"(
			"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(
				START WITH + 1 INCREMENT BY + 1 MINVALUE + 1 MAXVALUE + 9223372036854775807 NO CYCLE CACHE 20 NO ORDER
			),
			"NOMBRE" VARCHAR(100) NOT NULL,
			"CODIGO" VARCHAR(3) UNIQUE NOT NULL,
			"URL_SERVICIO" VARCHAR(255) NOT NULL,
			"URL_GESTION_INTERNA" VARCHAR(255),
			"URL_INFO_ADICIONAL" VARCHAR(255),
			"REGISTRA_ACTIVIDAD" CHAR(1) NOT NULL,
			"TIPO_INVOCACION" VARCHAR(30) NOT NULL,
			"CREATED_BY" VARCHAR(100) NOT NULL,
			"DATE_CREATED" DATE NOT NULL,
			"LAST_UPDATED" DATE NOT NULL,
			"UPDATED_BY" VARCHAR(100) NOT NULL
		);

ALTER TABLE
	"DBINTGEN" . "SERVICIO" ADD PRIMARY KEY("ID");

CREATE
	TABLE
		"DBINTGEN" . "SERVICIO_PARAMETRO"(
			"SERVICIO_ID" SMALLINT NOT NULL,
			"PARAMETRO_ID" VARCHAR(80) NOT NULL
		);

ALTER TABLE
	"DBINTGEN" . "SERVICIO_PARAMETRO" ADD UNIQUE(
		"SERVICIO_ID",
		"PARAMETRO_ID"
	);

ALTER TABLE
	"DBINTGEN"."SERVICIO_PARAMETRO" ADD FOREIGN KEY("SERVICIO_ID") REFERENCES "DBINTGEN" . "SERVICIO"("ID");